# Generated by Django 4.2.30 on 2026-05-23 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFolderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folders', models.JSONField(default=list)),
                ('assignments', models.JSONField(default=dict)),
                ('current_folder_id', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folder_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user folder state',
            },
        ),
    ]
